---
language: ruby
cache: bundler
rvm:
  - 2.7.2
env:
  - HUTCH_URI="amqp://guest:guest@127.0.0.1/"
  - HUTCH_ENABLE_HTTP_API_USE=false
services:
  - rabbitmq
before_install: gem install bundler -v 2.1.4
