---
language: ruby
cache: bundler
matrix:
  include:
    - rvm: 2.7.2
      gemfile: gemfiles/rails.5.2.gemfile
    - rvm: 3.0.4
      gemfile: gemfiles/rails.6.1.gemfile
    - rvm: 3.1.2
      gemfile: gemfiles/rails.7.0.gemfile
env:
  - HUTCH_URI="amqp://guest:guest@localhost:5672"
  - HUTCH_ENABLE_HTTP_API_USE=false
dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
  - postgresql
before_install: gem install bundler -v 2.1.4
