---
language: ruby
cache: bundler
rvm:
  - 2.7.2
env:
  - HUTCH_URI="amqp://guest:guest@localhost:5672"
  - HUTCH_ENABLE_HTTP_API_USE=false
dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
  - postgresql
before_install: gem install bundler -v 2.1.4
